### ISSUE TITLE
Implement `no-segments-on-sliced-layers`

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#25]
Sliced layers (Entities, Features, Widgets, Pages) should not have folders with conventional segment names in direct children.

- [ ] Write the rule
- [ ] Write positive test
- [ ] Write negative test
- [ ] Add documentation in form of a README and link that in the main README of the repo

**Comment by daniilsapa** [comment]
Hi guys! 
I have no experience in open-source software development yet. But I’m interested in it and would like to start somewhere. I chose this project because I really like FSD and have successfully implemented it in several projects in my company and my personal projects. I think you have done an outstanding job and I look forward to helping you where I can.

Could you assign this task to me? Or how it is done in your organization.

**Comment by illright** [comment]
Hi @daniilsapa! Glad to hear about your positive experience with FSD and thank you for taking the time to contribute. I assigned you to this ticket, so feel free to start working on it. If you need any help, I'll be here to answer any questions you have :)

**Comment by daniilsapa** [comment]
@illright 
Thank you! Starting working on it 👌

**Comment by daniilsapa** [comment]
@illright 
To avoid possible confusion, as far as I understand, there is a typo in the task description, instead of “Shared” it should say  “Entities”. Because the "Shared" layer is just segmented.

**Comment by illright** [comment]
@daniilsapa yes, that's correct, fixed the description

**Comment by daniilsapa** [comment]
@illright 
I created a PR for this feature. Could you review it when you have time? Thank you in advance

**Comment by daniilsapa** [comment]
Quality checks failed for my PR and I think I know why. I'm fixing it
