### ISSUE TITLE
Support individual rule options

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#69]
Depends on #67

Currently, the rule's `check` function has a signature `check(root: Folder, context?: Context): Promise<Array<Diagnostic>>`. This is limiting our ability to reasonably pass options to rules, so instead we should revise this to make the second optional argument be the options, if the rule requires them.

The context should be scrapped. It's currently only used to determine if the source file extension is `js` or `ts`, and that is not even implemented yet. Context should be passed to rules through `this` by binding them upon the plugin creation. That way, only the plugin developer is responsible for what appears in the context. The functionality of exposing certain services to plugin writers will probably be implemented through functions that plugin writers can import.

**Comment by daniilsapa** [comment]
@illright 
Could you assign this issue to me?

**Comment by daniilsapa** [comment]
@illright 
I started reviewing the scope of work for this task and had several questions:

Why should we bind the context in `this`? Isn't it more convenient to pass options as a third parameter and leave the context as is? `check(root: Folder, context?: Context, options?: Options)`. Maybe I don't yet see some hidden advantages behind binding the context with "this" in this case but it's just more explicit to pass an argument, in my opinion.  
Alternatively, we could make rule options a part of the context and pass them as another one of its fields.

It looks like each rule that can have options should declare an interface describing the shape of its options and export it. Then we re-export them in the entry point of the plugin, so the users can reference those interfaces if they e.g. need to create factory functions to create option objects or if they just need to refer to the options shape. Am I right?


### Other questions

Also, here are some questions that concern the overall new config epic and not specifically this task. Maybe we'll need to create additional issues for them.

I think we need to improve the config validation.
What if there are conflicts between config objects inside the config? Such a case is not handled so far.

```javascript
const config = [
    ...fsd.configs.recommended,
    {
      files: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'off',
      },
    },
    {
      ignores: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'off',
      },
    },
],
```

We need to implement a full-fledged mechanism for resolving and merging config objects. Because we have temporary simplified logic for that purpose?

```typescript
function mergeConfigObjects(config: Config) {
  // TODO: temporary simplified implementation.
  //  Implement handling the "files" and "ignores" globs in further updates.
  return config.reduce((acc: ConfigObject, item) => {
    if ('rules' in item) {
      return { ...acc, rules: { ...acc.rules, ...item.rules } }
    }

    return acc
  }, {})
}
```

And finally, we know that a file can be imported and can import other files. When we add a file to `ignores` we obviously do not parse the file contents to make checks. But the question is, should we ignore this file if we see it in the import list of other files?

**Comment by illright** [comment]
> Why should we bind the context in this? Isn't it more convenient to pass options as a third parameter and leave the context as is? check(root: Folder, context?: Context, options?: Options). Maybe I don't yet see some hidden advantages behind binding the context with "this" in this case but it's just more explicit to pass an argument, in my opinion.

My thought process was following: the Steiger core itself doesn't really need to provide context to rules — all the helper functionality and project information I can think of can be accessed by importing what you need (we would probably implement some kind of injection of project information like source file extensions). The only time I see context to be useful is when you want to customize a ruleset. For example, if your Pages layer is called `screens`, then you'd want that to be exposed to all the rules. Here's how I see it:
```ts
// a user, writing their steiger.config.ts
import fsd from "@feature-sliced/steiger-plugin";

export default [
  ...fsd.configs.custom({
    layerNames: {
      pages: "screens",
    },
  }),
];
```

```ts
// the plugin developer, writing a customizable config, context passed as `this`
const configs = {
  custom(options) {
    return [plugin, allRules.map(rule => ({ ...rule, check: check.bind(options) }))],
  }
};
```

It is also possible to do this when context is passed as an argument, I just like it a bit less:
```ts
// the plugin developer, writing a customizable config, context passed as argument
const configs = {
  custom(options) {
    return [plugin, allRules.map(rule => ({ ...rule, check: (root, ruleOptions) => check(root, options, ruleOptions) }))],
  }
};
```

> Alternatively, we could make rule options a part of the context and pass them as another field inside the context.

Nah, I think that'd be mixing up very different responsibilities. I expect the context to be provided by plugin developers as opposed to Steiger itself, whereas rule options have to be provided by Steiger.

> It looks like each rule that can have options should declare an interface describing the shape of its options and export it.

Yes, agreed. Then [Example 4](https://github.com/feature-sliced/steiger/discussions/53#discussioncomment-9980110) would not inline the options, but would rather import them from the rule and use them for typing.

---

> What if there are conflicts between config objects inside the config? Such a case is not handled so far.
>
> ```ts
> const config = [
>     ...fsd.configs.recommended,
>     {
>       files: ['./src/shared/**'],
>       rules: {
>         'fsd/public-api': 'off',
>       },
>     },
>     {
>       ignores: ['./src/shared/**'],
>       rules: {
>         'fsd/public-api': 'off',
>       },
>     },
> ],
> ```

This seems like a valid config to me (albeit a little strange). The first element (`.recommended`) enables all rules for all files, then the second one (with `files`) disables the `public-api` rule for Shared, then the third one (with `ignores`) disables the `public-api` for all files except for Shared. As a result, we basically have all rules except for `public-api` enabled for all files, and `public-api` is disabled for all files (`Shared + (AllFiles - Shared) = AllFiles`).

> ... or ...
>
> ```ts
> const config = [
>     ...fsd.configs.recommended,
>     {
>       files: ['./src/shared/**'],
>       rules: {
>         'fsd/public-api': 'off',
>       },
>     },
>     {
>       files: ['./src/shared/**'],
>       rules: {
>         'fsd/public-api': 'error',
>       },
>     },
> ],
> ```

This config is also valid, the later element overrides the earlier. So the result of this config is all rules enabled for all files, again.

> We need to implement a full-fledged mechanism for resolving and merging config objects.

Yes. I should probably write up a specification for that. In that specification, I will include the question you had about imports, as well as a couple other questions that I still don't have definite answers to. Thanks for bringing it all up!

**Comment by illright** [comment]
@daniilsapa I wrote up a proposed specification for the actual support of inclusion/exclusion, let me know what you think 

https://github.com/feature-sliced/steiger/issues/82

**Comment by daniilsapa** [comment]
Thanks for the comprehensive explanation, then yes, it makes sense to provide the context in "this".
