### ISSUE TITLE
Implement the inclusion/exclusion of files in the config

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#82]
## Specification
Here's my proposed mental model — since we run rules individually, let's consider a single rule at a time. For a rule, there are several cases:
1. **The rule is off for the entire codebase**  
   The solution here is simple — just don't run it
2. **The rule is off for a certain portion or portions A of a codebase, and enabled as `error` for the rest of the codebase**
   We create a clone of the VFS that excludes these portions A of the codebase and run the rule on the result. It will be as if these files simply don't exist. For the purposes of FSD, these files will be treated as "outside of the FSD root", so any references to these files from the FSD root are unregulated, and any references of FSD slices in these excluded files are invisible to the rules.
3. **The rule is off for a certain portion or portions A of a codebase, enabled as `warn` for different non-overlapping portions B, and then enabled as `error` for yet different non-overlapping portions C** (see diagram)  
   We create a clone of the VFS that includes B + C and run the rule on the result. Then we _somehow_* determine what the severity is

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ef9a6f5d-8ab5-4506-8a42-99932a38648e">

\* About determining severity. This is a difficult question, because some errors are about entire folders, and the config allows us to change severity of individual files. I suggest we make the `error` severity "viral", in the sense that if at least one file in the mentioned folder has severity `error`, then that diagnostic will have severity `error`, same for `warn`, going further down.

### 1. Config merging

First of all, I think all rule definitions (i.e. plugin array elements that add new rules) should be hoisted to the top, so the order should not prevent you from disabling a rule. For example, the following two configs should be identical:
```ts
export default [
  { rules: { 'fsd/public-api': 'error' } },
  { paths: 'src/shared/**', rules: { 'fsd/public-api': 'warn' } },
  fsd.plugin, // here it is last
]
```

```ts
export default [
  fsd.plugin, // here it is first
  { rules: { 'fsd/public-api': 'error' } },
  { paths: 'src/shared/**', rules: { 'fsd/public-api': 'warn' } },
]
```

With that out of the way, I propose that the result of merging a config array is a mapping of rule to a pair of VFSes, one for error, other for warn, where they are enabled. Initially it will be `new Map(rules.map(rule => [rule, { warn: null, error: initialVfs }]))`, but as the array elements are parsed, these VFSes should be updated individually for each rule. 

> [!NOTE]
> We can ignore performance for now, since at the start, there won't be that many rules, and the configs will probably not be too complicated. Later, we can profile and determine what should be optimized.

### 2. Running rules

When we run a rule, we have two VFSes (`{ warn, error }`), so ideally we should also implement a merge operator for VFSes. Then we merge the two VFSes, run the rule, get a list of diagnostics and determine the severity of each diagnostic with the algorithm proposed above

**Comment by daniilsapa** [comment]
Great job! Very straightforward

Yeah, plugins are already kind of hoisted, as we walk through the config array to find and process them first 

<img width="1005" alt="Screenshot 2024-08-15 at 00 39 38" src="https://github.com/user-attachments/assets/ddc68e25-d399-4e83-aca8-558f1d4b33b1">

But I'm a bit concerned by the 2 trees for warn and error. I don't understand if we are going to pass them both to a rule. If yes, then it seems to be an unnecessary over-complication. Because, In this case, we force guys who will develop plugins to come up with a tree merging operation, which could be too sophisticated for an average user. Of course, we can export a function for that purpose from the toolbox, but still.

Looks like a rule shouldn't even "know" about severities. It's just supplied with full VFS or a portion of VFS and collects diagnostics. Then Steiger core decides what to do with those diagnostics (whether to log it as a warning or an error)

We could have a map of FS node path to severity (generate such a map for each rule during the config parsing stage). So, we can quickly decide what to do with a diagnostic when it comes out of a rule.

**Comment by illright** [comment]
> But I'm a bit concerned by the 2 trees for warn and error. I don't understand if we are going to pass them both to a rule.

No, my intent was to merge the trees before passing them to the rule 

> Looks like a rule shouldn't even "know" about severities. It's just supplied with full VFS or a portion of VFS and collects diagnostics. Then Steiger core decides what to do with those diagnostics (whether to log it as a warning or an error)

Yes, I agree

**Comment by daniilsapa** [comment]
@illright 

```text
{
      files: <FilesDefinition>,
      Ignores: <IgnoresDefinition>,
      rules: {
        <RuleName>: <Severity> | [ <Severity>, <RuleOptions> ],
      },
}
```

From this structure, a user can conclude that it is possible to set different rule options for different parts of the VFS (since you can do that for "severity").
But it's not the case based on what we discussed.

So, here I listed ways we can solve the problem:
1. Think up some other way to provide rule options (just a different syntax, maybe a separate object type inside config), so it will be less misleading for the users
2. Use only the later options for a rule (and apply to the entire VFS disregarding files and ignores) and reflect that quirk in the documentation 
3. Implement the capability to have different rule options for different VFS part

My personal favorite way is the first one. But I would like to see your opinion on this issue. You may have alternative solutions.

**Comment by illright** [comment]
Hm, yes, very good point. Personally, I'm not a huge fan of the first solution, mostly because I don't have any ideas about alternative ways of providing options to rules. However, I am open to considering it if you have some proposals.

Ideally, we would have a system that allows different sets of options, and the way it could work is by running the rule on all non-disabled files as many times as there are different options and then discarding diagnostics that don't apply in selected files. However, this would probably involve a bunch of messy code and effort for a very narrow edge case. 

Therefore, I propose an adaptation of the second option. Instead of quietly accepting only the last option, I'd prefer if we threw a validation error if the config file specifies several different rule options. That way, this behaviour cannot be missed, and if it's a problem for anyone, we'll hear about it in the issues.

**Comment by illright** [comment]
Actually, wait, you had a proposal in your message for the first solution — a different kind of object in the config array. I would prefer to keep this option as a last resort, because it broadens the API (and also deviates from ESLint conventions) for all users to prevent a narrow edge case (in my opinion, it's narrow, let me know if you disagree). I'd prefer to keep the public API as small as possible and simply let people know when something isn't supported

**Comment by daniilsapa** [comment]
Yes, your addition to the second option sounds completely reasonable. Let's go with it 👍

> Ideally, we would have a system that allows different sets of options, and the way it could work is by running the rule on all non-disabled files as many times as there are different options and then discarding diagnostics that don't apply in selected files.

I agree, it's an absolute overkill at this stage.
